# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-hadolint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under , so your job can access it
      - uses: actions/checkout@v2

      - name: Run hadolint for Base testrunner bullseye
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: base/Dockerfile.bullseye
      - name: Run hadolint for Base testrunner bookworm
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: base/Dockerfile.bookworm
      - name: Run hadolint for Go
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: go/Dockerfile
      - name: Run hadolint for Python
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: python/Dockerfile
      - name: Run hadolint for Rust
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: rust/Dockerfile

  build-and-push:
    # Only run on push to main branch (PR merges)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: run-hadolint

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: base/Dockerfile.bookworm
            tag: bookworm
            context: base
            build_args: ""
          - dockerfile: base/Dockerfile.bullseye
            tag: bullseye
            context: base
            build_args: ""
          - dockerfile: python/Dockerfile
            tag: python
            context: python
            build_args: |
              DEBIAN_RELEASE=bookworm
              PYTHON_VERSION=3.13
          - dockerfile: go/Dockerfile
            tag: go
            context: go
            build_args: |
              DEBIAN_RELEASE=bookworm
              GO_VERSION=1.25.0
          - dockerfile: rust/Dockerfile
            tag: rust
            context: rust
            build_args: |
              DEBIAN_RELEASE=bookworm
              RUST_VERSION=1.90.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/eiffel-community/etos-base-test-runner
          tags: |
            type=raw,value=${{ matrix.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build_args }}
